# Generated by Django 2.2.2 on 2019-08-04 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190804_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='handle',
            field=models.CharField(error_messages={'unique': 'User with that handle already exists.'}, max_length=254, unique=True, verbose_name='handle'),
        ),
    ]
