version: '3'

services:
  db:
    image: kartoza/postgis
    volumes:
      - data-volume:/var/lib/db
    ports:
      - 25432:5432
  web:
    build: .
    # TODO - Must fix. Having to disable reload to use ipdb.
    # to get a container up and working with ipdb
    # docker-compose run --rm --service-ports web
    command: python3 manage.py runserver 0.0.0.0:8000 --noreload
    # command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    stdin_open: true
    tty: true

volumes:
  data-volume:
