# Generated by Django 2.2.8 on 2020-02-05 19:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_location_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='components',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='location',
            name='type',
            field=models.CharField(choices=[('village', 'Village'), ('neighbourhood', 'Neighbourhood'), ('city', 'City'), ('county', 'County'), ('postcode', 'Postcode'), ('terminated_postcode', 'Terminated Postcode'), ('state_district', 'State District'), ('state', 'State'), ('region', 'Region'), ('island', 'Island'), ('country', 'Country'), ('unknown', 'Unknown')], default='unknown', max_length=254),
        ),
    ]
