# Generated by Django 2.2.8 on 2020-02-14 17:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_location_extra_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='name',
            field=models.CharField(default='', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='components',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
