# Generated by Django 2.2.8 on 2020-02-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_add_name_to_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
