# Generated by Django 2.2.2 on 2019-08-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
