# Generated by Django 2.2.8 on 2020-02-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='end_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
