# Generated by Django 2.2.8 on 2020-02-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0002_set_default_for_gig_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='title',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='gig',
            name='venue',
            field=models.CharField(max_length=254),
        ),
    ]
