# Generated by Django 2.2.4 on 2019-11-11 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_remove_unique_from_location_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
